#!/bin/sh
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs devtmpfs /dev
/sbin/mdev -s
mkdir -p /dev/pts
mount -vt devpts -o gid=4,mode=620 none /dev/pts
chmod 666 /dev/ptmx

/sbin/ip link set eth0 up
/sbin/ip addr add 10.0.2.15/24 dev eth0
/sbin/ip link set lo up
/sbin/ip addr add 127.0.0.1/8 dev lo

insmod /root/holstein.ko
mknod -m 666 /dev/holstein c `grep holstein /proc/devices | awk '{print $1;}'` 0

setsid /bin/cttyhack setuidgid 500 /bin/sh
#setsid /bin/cttyhack setuidgid 0 /bin/sh

umount /proc
umount /sys
poweroff -d 0 -f
